// Define the operating system and some other configurations
   #define WINDOWS
// #define DOS
// #define LINUX
// #define UNIX
// #define MACOS
// #define BSD
// #define ANDROID
// #define IOS
// #define WEB
// #define QT
// #define SDL
// #define OPENGL
// #define DIRECTX
// #define VULKAN
// #define METAL
// #define WEBGL
// #define UNITY
// #define UNREAL
// #define GODOT
// #define GAME_ENGINE
// #define CONSOLE
// #define CONSOLE_WINDOWS
// #define CONSOLE_LINUX
// #define CONSOLE_WIN_CMD
// #define CONSOLE_WIN_POWERSHELL
// #define WINDOWS_2D
// #define DOS_2D
// #define LINUX_2D
// #define UNIX_2D
// #define MACOS_2D
// #define BSD_2D
// #define ANDROID_2D
// #define IOS_2D
// #define WEB_2D
// #define QT_2D
// #define SDL_2D
// #define OPENGL_2D
// #define DIRECTX_2D
// #define VULKAN_2D
// #define METAL_2D
// #define WEBGL_2D
// #define UNITY_2D
// #define UNREAL_2D
// #define GODOT_2D
// #define GAME_ENGINE_2D
// #define CONSOLE_2D
// #define CONSOLE_WINDOWS_2D
// #define CONSOLE_LINUX_2D
// #define CONSOLE_WIN_CMD_2D
// #define CONSOLE_WIN_POWERSHELL_2D
// #define WINDOWS_LAYERS
// #define LINUX_LAYERS
// #define MACOS_LAYERS
// #define ANDROID_LAYERS
// #define IOS_LAYERS
// #define WEB_LAYERS
// #define QT_LAYERS
// #define SDL_LAYERS
// #define OPENGL_LAYERS
// #define DIRECTX_LAYERS
// #define VULKAN_LAYERS
// #define METAL_LAYERS
// #define WEBGL_LAYERS
// #define UNITY_LAYERS
// #define UNREAL_LAYERS
// #define GODOT_LAYERS
// #define GAME_ENGINE_LAYERS
